/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns the URL for authorization via Microsoft */
    get: operations['AuthController_url'];
    put?: never;
    /** Authenticates a user or creates a new one if they do not exist using the code received from Microsoft */
    post: operations['AuthController_microsoft'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refreshes the access token using the refresh token and returns the current user with a new set of tokens */
    post: operations['AuthController_refreshToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/constructor-categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns all existing constructor categories */
    get: operations['ConstructorCategoriesController_all'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/constructor-category': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Creates new constructor category */
    post: operations['ConstructorCategoryController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/constructor-items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ConstructorItemsController_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/constructor-item': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Creates new constructor item */
    post: operations['ConstructorItemController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthUrlDto: {
      /** @description Microsoft auth url */
      url: string;
    };
    AuthMicrosoftDto: {
      /** @description Microsoft OAuth code */
      code: string;
    };
    UserDto: {
      /** @description Microsoft ID */
      microsoft_id: string;
      /** @description Minecraft UUID */
      uuid: string;
      /** @description Minecraft name */
      name: string;
      /**
       * @description User role
       * @default user
       * @enum {string}
       */
      role: 'user' | 'admin';
      minecraft_active_skin: {
        id: string;
        /** @enum {string} */
        variant: 'CLASSIC' | 'SLIM';
        url: string;
      };
    };
    ConstructorCategoriesDto: {
      /** @description ID */
      id: string;
      children: {
        /** @description ID */
        id: string;
      }[];
    }[];
    ConstructorCategoryCreateDto: {
      /** @description ID */
      id: string;
      /** @description Parent category ID */
      parent?: string;
    };
    ConstructorCategoryDto: {
      /** @description ID */
      id: string;
      children: {
        /** @description ID */
        id: string;
      }[];
    };
    PaginatedMetaDocumented: {
      /** Number of items per page */
      itemsPerPage: number;
      /** Total number of items */
      totalItems: number;
      /** Current requested page */
      currentPage: number;
      /** Total number of pages */
      totalPages: number;
      /** Sorting by columns */
      sortBy?: (string | ('ASC' | 'DESC'))[][];
      /** Search by fields */
      searchBy?: string[];
      /** Search term */
      search?: string;
      /** List of selected fields */
      select?: string[];
      /** Filters that applied to the query */
      filter?: Record<string, never>;
    };
    PaginatedLinksDocumented: {
      /** Link to first page */
      first?: string;
      /** Link to previous page */
      previous?: string;
      /** Link to current page */
      current?: string;
      /** Link to next page */
      next?: string;
      /** Link to last page */
      last?: string;
    };
    PaginatedDocumented: {
      /** Array of entities */
      data: Record<string, never>[];
      /** Pagination Metadata */
      meta: components['schemas']['PaginatedMetaDocumented'];
      /** Links to pages */
      links: components['schemas']['PaginatedLinksDocumented'];
    };
    ConstructorItemDto: {
      /** @description ID */
      id: string;
      /** @description Image url */
      url: string;
      /** @description Title */
      title: string;
      /** @description Description */
      description: string;
      /**
       * @description Variant
       * @enum {string}
       */
      variant: 'CLASSIC' | 'SLIM';
    };
    ConstructorItemCreateDto: {
      /** @description Title */
      title: string;
      /** @description Description */
      description: string;
      /**
       * @description Variant
       * @enum {string}
       */
      variant: 'CLASSIC' | 'SLIM';
      /** @description Item category id */
      category: string;
      file: unknown;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_url: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthUrlDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example validation_error */
            error: string;
            /** @example example_field: Required, example_field: Input not instance of File */
            message: string;
          };
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example required_auth */
            error: string;
            /** @example This method required authorization */
            message: string;
          };
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example unknown_method */
            error: string;
            /** @example Unknown method */
            message: string;
          };
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example internal */
            error: string;
            /** @example Internal exception message */
            message: string;
          };
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example empty_login_url */
            error: string;
            /** @example Empty login url */
            message: string;
          };
        };
      };
    };
  };
  AuthController_microsoft: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AuthMicrosoftDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example validation_error */
            error: string;
            /** @example example_field: Required, example_field: Input not instance of File */
            message: string;
          };
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example required_auth */
            error: string;
            /** @example This method required authorization */
            message: string;
          };
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example invalid_code */
            error: string;
            /** @example Invalid Microsoft authorization code */
            message: string;
          };
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example unknown_method */
            error: string;
            /** @example Unknown method */
            message: string;
          };
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example internal */
            error: string;
            /** @example Internal exception message */
            message: string;
          };
        };
      };
    };
  };
  AuthController_refreshToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          'Access-Token': string;
          'Refresh-Token': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example validation_error */
            error: string;
            /** @example example_field: Required, example_field: Input not instance of File */
            message: string;
          };
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example required_auth */
            error: string;
            /** @example This method required authorization */
            message: string;
          };
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example unknown_method */
            error: string;
            /** @example Unknown method */
            message: string;
          };
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example internal */
            error: string;
            /** @example Internal exception message */
            message: string;
          };
        };
      };
    };
  };
  ConstructorCategoriesController_all: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConstructorCategoriesDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example validation_error */
            error: string;
            /** @example example_field: Required, example_field: Input not instance of File */
            message: string;
          };
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example required_auth */
            error: string;
            /** @example This method required authorization */
            message: string;
          };
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example unknown_method */
            error: string;
            /** @example Unknown method */
            message: string;
          };
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example internal */
            error: string;
            /** @example Internal exception message */
            message: string;
          };
        };
      };
    };
  };
  ConstructorCategoryController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConstructorCategoryCreateDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConstructorCategoryDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example validation_error */
            error: string;
            /** @example example_field: Required, example_field: Input not instance of File */
            message: string;
          };
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example required_auth */
            error: string;
            /** @example This method required authorization */
            message: string;
          };
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example unknown_method */
            error: string;
            /** @example Unknown method */
            message: string;
          };
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example internal */
            error: string;
            /** @example Internal exception message */
            message: string;
          };
        };
      };
    };
  };
  ConstructorItemsController_get: {
    parameters: {
      query?: {
        /** @description Page number to retrieve.If you provide invalid value the default page number will applied
         *             <p>
         *                  <b>Example: </b> 1
         *               </p>
         *             <p>
         *                  <b>Default Value: </b> 1
         *               </p>
         *              */
        'page'?: number;
        /** @description Number of records per page.
         *           <p>
         *                  <b>Example: </b> 20
         *               </p>
         *           <p>
         *                  <b>Default Value: </b> 20
         *               </p>
         *           <p>
         *                  <b>Max Value: </b> 20
         *               </p>
         *
         *           If provided value is greater than max value, max value will be applied.
         *            */
        'limit'?: number;
        /** @description Filter by category.id query param.
         *               <p>
         *                  <b>Format: </b> filter.category.id={$not}:OPERATION:VALUE
         *               </p>
         *               <p>
         *                  <b>Example: </b> filter.category.id=$not:$like:John Doe&filter.category.id=like:John
         *               </p>
         *               <h4>Available Operations</h4><ul><li>$eq</li></ul> */
        'filter.category.id'?: string[];
        /** @description Parameter to sort by.
         *           <p>To sort by multiple fields, just provide query param multiple types. The order in url defines an order of sorting</p>
         *           <p>
         *                  <b>Format: </b> fieldName:DIRECTION
         *               </p>
         *           <p>
         *                  <b>Example: </b> sortBy=id:DESC&sortBy=createdAt:ASC
         *               </p>
         *           <p>
         *                  <b>Default Value: </b> id:DESC
         *               </p>
         *           <h4>Available Fields</h4><ul><li>id</li>
         *     <li>title</li>
         *     <li>description</li>
         *     <li>variant</li></ul>
         *            */
        'sortBy'?: (
          | 'id:ASC'
          | 'id:DESC'
          | 'title:ASC'
          | 'title:DESC'
          | 'description:ASC'
          | 'description:DESC'
          | 'variant:ASC'
          | 'variant:DESC'
        )[];
        /** @description Search term to filter result values
         *             <p>
         *                  <b>Example: </b> John
         *               </p>
         *             <p>
         *                  <b>Default Value: </b> No default value
         *               </p>
         *              */
        'search'?: string;
        /** @description List of fields to search by term to filter result values
         *             <p>
         *                  <b>Example: </b> title,description
         *               </p>
         *             <p>
         *                  <b>Default Value: </b> By default all fields mentioned below will be used to search by term
         *               </p>
         *             <h4>Available Fields</h4><ul><li>title</li>
         *     <li>description</li></ul>
         *              */
        'searchBy'?: string[];
        /** @description List of fields to select.
         *           <p>
         *                  <b>Example: </b> id,title,description,variant,category.id
         *               </p>
         *           <p>
         *                  <b>Default Value: </b> By default all fields returns. If you want to select only some fields, provide them in query param
         *               </p>
         *            */
        'select'?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedDocumented'] & {
            data?: components['schemas']['ConstructorItemDto'][];
            meta?: {
              select?: (
                | 'id'
                | 'title'
                | 'description'
                | 'variant'
                | 'category.id'
                | 'owner.uuid'
                | 'owner.name'
                | 'owner.minecraft_active_skin'
              )[];
              filter?: {
                'category.id'?: string | string[];
              };
            };
          };
        };
      };
    };
  };
  ConstructorItemController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['ConstructorItemCreateDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConstructorCategoryDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example validation_error */
            error: string;
            /** @example example_field: Required, example_field: Input not instance of File */
            message: string;
          };
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example required_auth */
            error: string;
            /** @example This method required authorization */
            message: string;
          };
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example unknown_method */
            error: string;
            /** @example Unknown method */
            message: string;
          };
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example internal */
            error: string;
            /** @example Internal exception message */
            message: string;
          };
        };
      };
    };
  };
}
