/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as Import } from './routes/~*'

// Create Virtual Routes

const ConstructorLazyImport = createFileRoute('/_constructor')()
const IndexLazyImport = createFileRoute('/')()
const ConstructorConstructorLazyImport = createFileRoute(
  '/_constructor/constructor',
)()
const ConnectionsMicrosoftIndexLazyImport = createFileRoute(
  '/connections/microsoft/',
)()
const ConstructorConstructorUploadIndexLazyImport = createFileRoute(
  '/_constructor/constructor/upload/',
)()
const ConstructorConstructorCategorycreateIndexLazyImport = createFileRoute(
  '/_constructor/constructor/category_create/',
)()

// Create/Update Routes

const ConstructorLazyRoute = ConstructorLazyImport.update({
  id: '/_constructor',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~_constructor.lazy').then((d) => d.Route))

const Route = Import.update({
  id: '/*',
  path: '/*',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~index.lazy').then((d) => d.Route))

const ConstructorConstructorLazyRoute = ConstructorConstructorLazyImport.update(
  {
    id: '/constructor',
    path: '/constructor',
    getParentRoute: () => ConstructorLazyRoute,
  } as any,
).lazy(() =>
  import('./routes/~_constructor/~constructor.lazy').then((d) => d.Route),
)

const ConnectionsMicrosoftIndexLazyRoute =
  ConnectionsMicrosoftIndexLazyImport.update({
    id: '/connections/microsoft/',
    path: '/connections/microsoft/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/~connections/~microsoft/~index.lazy').then((d) => d.Route),
  )

const ConstructorConstructorUploadIndexLazyRoute =
  ConstructorConstructorUploadIndexLazyImport.update({
    id: '/upload/',
    path: '/upload/',
    getParentRoute: () => ConstructorConstructorLazyRoute,
  } as any).lazy(() =>
    import('./routes/~_constructor/~constructor.upload/~index.lazy').then(
      (d) => d.Route,
    ),
  )

const ConstructorConstructorCategorycreateIndexLazyRoute =
  ConstructorConstructorCategorycreateIndexLazyImport.update({
    id: '/category_create/',
    path: '/category_create/',
    getParentRoute: () => ConstructorConstructorLazyRoute,
  } as any).lazy(() =>
    import(
      './routes/~_constructor/~constructor.category_create/~index.lazy'
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/*': {
      id: '/*'
      path: '/*'
      fullPath: '/*'
      preLoaderRoute: typeof Import
      parentRoute: typeof rootRoute
    }
    '/_constructor': {
      id: '/_constructor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ConstructorLazyImport
      parentRoute: typeof rootRoute
    }
    '/_constructor/constructor': {
      id: '/_constructor/constructor'
      path: '/constructor'
      fullPath: '/constructor'
      preLoaderRoute: typeof ConstructorConstructorLazyImport
      parentRoute: typeof ConstructorLazyImport
    }
    '/connections/microsoft/': {
      id: '/connections/microsoft/'
      path: '/connections/microsoft'
      fullPath: '/connections/microsoft'
      preLoaderRoute: typeof ConnectionsMicrosoftIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_constructor/constructor/category_create/': {
      id: '/_constructor/constructor/category_create/'
      path: '/category_create'
      fullPath: '/constructor/category_create'
      preLoaderRoute: typeof ConstructorConstructorCategorycreateIndexLazyImport
      parentRoute: typeof ConstructorConstructorLazyImport
    }
    '/_constructor/constructor/upload/': {
      id: '/_constructor/constructor/upload/'
      path: '/upload'
      fullPath: '/constructor/upload'
      preLoaderRoute: typeof ConstructorConstructorUploadIndexLazyImport
      parentRoute: typeof ConstructorConstructorLazyImport
    }
  }
}

// Create and export the route tree

interface ConstructorConstructorLazyRouteChildren {
  ConstructorConstructorCategorycreateIndexLazyRoute: typeof ConstructorConstructorCategorycreateIndexLazyRoute
  ConstructorConstructorUploadIndexLazyRoute: typeof ConstructorConstructorUploadIndexLazyRoute
}

const ConstructorConstructorLazyRouteChildren: ConstructorConstructorLazyRouteChildren =
  {
    ConstructorConstructorCategorycreateIndexLazyRoute:
      ConstructorConstructorCategorycreateIndexLazyRoute,
    ConstructorConstructorUploadIndexLazyRoute:
      ConstructorConstructorUploadIndexLazyRoute,
  }

const ConstructorConstructorLazyRouteWithChildren =
  ConstructorConstructorLazyRoute._addFileChildren(
    ConstructorConstructorLazyRouteChildren,
  )

interface ConstructorLazyRouteChildren {
  ConstructorConstructorLazyRoute: typeof ConstructorConstructorLazyRouteWithChildren
}

const ConstructorLazyRouteChildren: ConstructorLazyRouteChildren = {
  ConstructorConstructorLazyRoute: ConstructorConstructorLazyRouteWithChildren,
}

const ConstructorLazyRouteWithChildren = ConstructorLazyRoute._addFileChildren(
  ConstructorLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/*': typeof Route
  '': typeof ConstructorLazyRouteWithChildren
  '/constructor': typeof ConstructorConstructorLazyRouteWithChildren
  '/connections/microsoft': typeof ConnectionsMicrosoftIndexLazyRoute
  '/constructor/category_create': typeof ConstructorConstructorCategorycreateIndexLazyRoute
  '/constructor/upload': typeof ConstructorConstructorUploadIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/*': typeof Route
  '': typeof ConstructorLazyRouteWithChildren
  '/constructor': typeof ConstructorConstructorLazyRouteWithChildren
  '/connections/microsoft': typeof ConnectionsMicrosoftIndexLazyRoute
  '/constructor/category_create': typeof ConstructorConstructorCategorycreateIndexLazyRoute
  '/constructor/upload': typeof ConstructorConstructorUploadIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/*': typeof Route
  '/_constructor': typeof ConstructorLazyRouteWithChildren
  '/_constructor/constructor': typeof ConstructorConstructorLazyRouteWithChildren
  '/connections/microsoft/': typeof ConnectionsMicrosoftIndexLazyRoute
  '/_constructor/constructor/category_create/': typeof ConstructorConstructorCategorycreateIndexLazyRoute
  '/_constructor/constructor/upload/': typeof ConstructorConstructorUploadIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/*'
    | ''
    | '/constructor'
    | '/connections/microsoft'
    | '/constructor/category_create'
    | '/constructor/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/*'
    | ''
    | '/constructor'
    | '/connections/microsoft'
    | '/constructor/category_create'
    | '/constructor/upload'
  id:
    | '__root__'
    | '/'
    | '/*'
    | '/_constructor'
    | '/_constructor/constructor'
    | '/connections/microsoft/'
    | '/_constructor/constructor/category_create/'
    | '/_constructor/constructor/upload/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  Route: typeof Route
  ConstructorLazyRoute: typeof ConstructorLazyRouteWithChildren
  ConnectionsMicrosoftIndexLazyRoute: typeof ConnectionsMicrosoftIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  Route: Route,
  ConstructorLazyRoute: ConstructorLazyRouteWithChildren,
  ConnectionsMicrosoftIndexLazyRoute: ConnectionsMicrosoftIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/*",
        "/_constructor",
        "/connections/microsoft/"
      ]
    },
    "/": {
      "filePath": "~index.lazy.tsx"
    },
    "/*": {
      "filePath": "~*.tsx"
    },
    "/_constructor": {
      "filePath": "~_constructor.lazy.tsx",
      "children": [
        "/_constructor/constructor"
      ]
    },
    "/_constructor/constructor": {
      "filePath": "~_constructor/~constructor.lazy.tsx",
      "parent": "/_constructor",
      "children": [
        "/_constructor/constructor/category_create/",
        "/_constructor/constructor/upload/"
      ]
    },
    "/connections/microsoft/": {
      "filePath": "~connections/~microsoft/~index.lazy.tsx"
    },
    "/_constructor/constructor/category_create/": {
      "filePath": "~_constructor/~constructor.category_create/~index.lazy.tsx",
      "parent": "/_constructor/constructor"
    },
    "/_constructor/constructor/upload/": {
      "filePath": "~_constructor/~constructor.upload/~index.lazy.tsx",
      "parent": "/_constructor/constructor"
    }
  }
}
ROUTE_MANIFEST_END */
