/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'

// Create Virtual Routes

const ConstructorLazyImport = createFileRoute('/_constructor')()
const IndexLazyImport = createFileRoute('/')()
const ConstructorConstructorLazyImport = createFileRoute(
  '/_constructor/constructor',
)()
const ConnectionsMicrosoftIndexLazyImport = createFileRoute(
  '/connections/microsoft/',
)()
const ConstructorConstructorUploaditemIndexLazyImport = createFileRoute(
  '/_constructor/constructor/upload_item/',
)()

// Create/Update Routes

const ConstructorLazyRoute = ConstructorLazyImport.update({
  id: '/_constructor',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~_constructor.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~index.lazy').then((d) => d.Route))

const ConstructorConstructorLazyRoute = ConstructorConstructorLazyImport.update(
  {
    path: '/constructor',
    getParentRoute: () => ConstructorLazyRoute,
  } as any,
).lazy(() =>
  import('./routes/~_constructor/~constructor.lazy').then((d) => d.Route),
)

const ConnectionsMicrosoftIndexLazyRoute =
  ConnectionsMicrosoftIndexLazyImport.update({
    path: '/connections/microsoft/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/~connections/~microsoft/~index.lazy').then((d) => d.Route),
  )

const ConstructorConstructorUploaditemIndexLazyRoute =
  ConstructorConstructorUploaditemIndexLazyImport.update({
    path: '/upload_item/',
    getParentRoute: () => ConstructorConstructorLazyRoute,
  } as any).lazy(() =>
    import('./routes/~_constructor/~constructor.upload_item/~index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_constructor': {
      id: '/_constructor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ConstructorLazyImport
      parentRoute: typeof rootRoute
    }
    '/_constructor/constructor': {
      id: '/_constructor/constructor'
      path: '/constructor'
      fullPath: '/constructor'
      preLoaderRoute: typeof ConstructorConstructorLazyImport
      parentRoute: typeof ConstructorLazyImport
    }
    '/connections/microsoft/': {
      id: '/connections/microsoft/'
      path: '/connections/microsoft'
      fullPath: '/connections/microsoft'
      preLoaderRoute: typeof ConnectionsMicrosoftIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_constructor/constructor/upload_item/': {
      id: '/_constructor/constructor/upload_item/'
      path: '/upload_item'
      fullPath: '/constructor/upload_item'
      preLoaderRoute: typeof ConstructorConstructorUploaditemIndexLazyImport
      parentRoute: typeof ConstructorConstructorLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ConstructorLazyRoute: ConstructorLazyRoute.addChildren({
    ConstructorConstructorLazyRoute:
      ConstructorConstructorLazyRoute.addChildren({
        ConstructorConstructorUploaditemIndexLazyRoute,
      }),
  }),
  ConnectionsMicrosoftIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "children": [
        "/",
        "/_constructor",
        "/connections/microsoft/"
      ]
    },
    "/": {
      "filePath": "~index.lazy.tsx"
    },
    "/_constructor": {
      "filePath": "~_constructor.lazy.tsx",
      "children": [
        "/_constructor/constructor"
      ]
    },
    "/_constructor/constructor": {
      "filePath": "~_constructor/~constructor.lazy.tsx",
      "parent": "/_constructor",
      "children": [
        "/_constructor/constructor/upload_item/"
      ]
    },
    "/connections/microsoft/": {
      "filePath": "~connections/~microsoft/~index.lazy.tsx"
    },
    "/_constructor/constructor/upload_item/": {
      "filePath": "~_constructor/~constructor.upload_item/~index.lazy.tsx",
      "parent": "/_constructor/constructor"
    }
  }
}
ROUTE_MANIFEST_END */
