/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ConstructorIndexLazyImport = createFileRoute('/constructor/')()
const ConnectionsMicrosoftIndexLazyImport = createFileRoute(
  '/connections/microsoft/',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~index.lazy').then((d) => d.Route))

const ConstructorIndexLazyRoute = ConstructorIndexLazyImport.update({
  path: '/constructor/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/~constructor/~index.lazy').then((d) => d.Route),
)

const ConnectionsMicrosoftIndexLazyRoute =
  ConnectionsMicrosoftIndexLazyImport.update({
    path: '/connections/microsoft/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/~connections/~microsoft/~index.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/constructor/': {
      id: '/constructor/'
      path: '/constructor'
      fullPath: '/constructor'
      preLoaderRoute: typeof ConstructorIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/connections/microsoft/': {
      id: '/connections/microsoft/'
      path: '/connections/microsoft'
      fullPath: '/connections/microsoft'
      preLoaderRoute: typeof ConnectionsMicrosoftIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ConstructorIndexLazyRoute,
  ConnectionsMicrosoftIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "children": [
        "/",
        "/constructor/",
        "/connections/microsoft/"
      ]
    },
    "/": {
      "filePath": "~index.lazy.tsx"
    },
    "/constructor/": {
      "filePath": "~constructor/~index.lazy.tsx"
    },
    "/connections/microsoft/": {
      "filePath": "~connections/~microsoft/~index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
