/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the URL for authorization via Microsoft */
        get: operations["AuthController_url"];
        put?: never;
        /** Authenticates a user or creates a new one if they do not exist using the code received from Microsoft */
        post: operations["AuthController_microsoft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refreshes the access token using the refresh token and returns the current user with a new set of tokens */
        post: operations["AuthController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constructor-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ConstructorCategoryController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constructor-item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ConstructorItemController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthUrlDto: {
            /** @description Microsoft auth url */
            url: string;
        };
        AuthMicrosoftDto: {
            /** @description Microsoft OAuth code */
            code: string;
        };
        UserDto: {
            /** @description Microsoft ID */
            microsoft_id: string;
            /** @description Minecraft UUID */
            uuid: string;
            /** @description Minecraft name */
            name: string;
            /**
             * @description User role
             * @default user
             * @enum {string}
             */
            role: "user" | "admin";
            minecraft_active_skin: {
                id: string;
                /** @enum {string} */
                variant: "CLASSIC" | "SLIM";
                url: string;
            };
        };
        ConstructorCategoryCreateDto: {
            /** @description ID */
            id: string;
            /** @description Parent category ID */
            parent?: string;
        };
        ConstructorItemCreateDto: {
            /** @description Title */
            title: string;
            /** @description Description */
            description: string;
            /**
             * @description Variant
             * @enum {string}
             */
            variant: "CLASSIC" | "SLIM";
            /** @description Item category id */
            category: string;
            file: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_url: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUrlDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "validation_error",
                         *       "message": "example_field: Required, example_field: Input not instance of File"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "required_auth",
                         *       "message": "This method required authorization"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "unknown_method",
                         *       "message": "Unknown method"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "internal",
                         *       "message": "Internal exception message"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "empty_login_url",
                         *       "message": "Empty login url"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
        };
    };
    AuthController_microsoft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthMicrosoftDto"][];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "validation_error",
                         *       "message": "example_field: Required, example_field: Input not instance of File"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "required_auth",
                         *       "message": "This method required authorization"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "invalid_code",
                         *       "message": "Invalid Microsoft authorization code"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "unknown_method",
                         *       "message": "Unknown method"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "internal",
                         *       "message": "Internal exception message"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
        };
    };
    AuthController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "validation_error",
                         *       "message": "example_field: Required, example_field: Input not instance of File"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "required_auth",
                         *       "message": "This method required authorization"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "unknown_method",
                         *       "message": "Unknown method"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example {
                         *       "code": "internal",
                         *       "message": "Internal exception message"
                         *     } */
                        error: Record<string, never>;
                    };
                };
            };
        };
    };
    ConstructorCategoryController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConstructorCategoryCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConstructorItemController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ConstructorItemCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
